---
title: Works
---

## **JOURNAL PUBLICATIONS**

#### **Takano, R.** & Nomura, M. Awe liberates the feeling that "my body is mine" [**Cognition and Emotion**](https://doi.org/10.1080/02699931.2020.1862765), Advance online publication. [Preprint](https://osf.io/f6vd3/), [OSF](https://osf.io/3w2er/)

#### **Takano, R.**, Taka, F., & Nomura, M. Development of Japanese versions of the Right-Wing Authoritarianism (RWA) scale. [**The Japanese Journal of Psychology**](https://doi.org/10.4992/jjpsy.91.19225), 91(6), 398-408. (in Japanese with English Abstract) 

#### **Takano, R.** & Nomura, M. Neural representations of awe: Distinguishing the common and distinct neural mechanisms [**Emotion**](https://doi.org/10.1037/emo0000771), Advance online publication. [Preprint](https://psyarxiv.com/qk8dn/), [OSF](https://osf.io/nxy7a/)

#### **Takano, R.** & Nomura, M. (2019). Anodal transcranial Direct Current Stimulation of the Right Temporoparietal Junction Enhances the Self-effacing Bias in Japanese Individuals [**Culture and Brain**]("https://doi.org/10.1007/s40167-018-0064-4"), 7, 80-91. 

<br>

## **FELLOWSHIPS, HONORS & AWARDS**

#### Excellent Presentation Award (The Japanese Psychological Association, 2019)

#### KAKENHI Grant-in-Aid for JSPS Fellows (2019-2022)

#### International Travel Grant (Global Education Office, Graduate School of Education, 2018)

#### Travel Award (The Japanese Psychological Association, 2017)
<br>

## **CONFERENCE PRESENTATIONS**

#### **Takano, R.** & Nomura, M. (2020). Awe Liberates the Sense of Self: A Small-Self Increases Sensitivity to the Rubber-Hand Illusion. _APS Virtual Poster Showcase_. June-September.

#### **Takano, R.** & Nomura, M. (2019). Neural Basis of Aesthetic Emotion: Origin of Prosocial Behavior and Aggression. _6th Congress of Asian College of Neuropsychopharmacology_, Fukuoka, Japan. Oct 10-Oct 12.

#### Hiraoka, D., **Takano, R.**, Kihara, M., Hayashi, M., & Nomura, M. (2019).  Cognitive load induces maternal approach behaviour to infant vocalisation, _British Psychological Society_, Stoke on Trent, UK, September 4.

#### **Takano, R.** & Nomura, M. (2018). Interdependent worldviews evoked by threat-based awe in Japan. _The 24th Congress of the International Association for Cross-Cultural Psychology_, Guelph, Canada. July 1-July 5.

#### **Takano, R.** & Nomura, M. (2018). The dark side of awe: From the perspective of intergroup conflict. _The 19th Annual Meeting of Society for Personality and Social Psychology_, Atlanta, Georgia, USA, March 1-3.
<br>

## **INVITED TALKS**
#### Osaka University	, December 2018



